### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by maedoc** [maedoc/sddekit#100]
Need a strategy for documentation. 

- [ ] C lib, primarily the header, written in doxygen format, but consider [Breathe](https://breathe.readthedocs.org/en/latest/) to put everything into Sphinx on readthedocs.org
- [ ] Python, Sphinx is natural choice
- [ ] MATLAB has its own system.
- [ ] Q: use GitHub wiki or not?

**Comment by abheekg** [comment]
Try to use, understand and start development is taking lot of time. An example can be updated in the docs or some more info can be provided how the code has been managed and distributed in python, C and Matlab.

**Comment by maedoc** [comment]
If you have `gcc` and `make`, you should be able to 

```bash
make
make bench_net_exc
```

to build the library and a benchmark example. Have you tried that? We can add more instructions on how to profile, and so on. 

As for documenting the library itself, I will build the Doxygen HTML docs and put them somewhere visible.

**Comment by maedoc** [comment]
Also, I moved the MATLAB and python bindings to separate branches / pull requests until they are stable. The git master branch is currently only for C lib.

**Comment by abheekg** [comment]
@maedoc I have built the tests and benchmark. I also studied the code extensively, especially the /src directory. With the long sequence on function pointers I was unable to find some function definitions (like user_apply(..) ). The code is highly functional, it would be helpful if you can give a deeper picture of how the toolkit is intended to work and how I can contribute. 

I have very good experience in C and good familiarity with make and other common software development tools etc. I am a student and have some background of numerical computation. I have ongoing courses on numerical (like Monte Carlo Stimulation) & parallel programming (but mostly in cuda). I would like to get seriously involved in the project.

P. S. I found this the only place to contact.

**Comment by maedoc** [comment]
@abheekg you can find my email on my github profile page, feel free to contact me there

The goal of the toolkit is to support computational & theoretical modeling research, letting the user set up and run a simulation with desired components (solver, integration scheme, nonlinear stochastic delay differential equation (SDDE) system, outputs, etc), either predefined or provided by user. It's currently quite new (first commit in December), which is why high-level, tutorial style documentation is currently lacking, though I've updated README (even with picutres). Currently I am working bindings for MATLAB & Python, and then demos & tutorial documentation is the next step.

re: function pointers, sorry I know, but this is a useful technique to depend on the interface and not implementation details (see Go & Java for languages which live by this rule). Usually, the c file where the implementation lies will build the struct of function pointers, see [this output object](https://github.com/maedoc/sddekit/blob/master/src/out_until.c) for example (which serves just to stop the simulation after a certain amount of time).

I've labeled a [few issues with the label "C"](https://github.com/maedoc/sddekit/issues?q=is%3Aopen+is%3Aissue+label%3Ac) to identify useful contributions a C programmer could make; ask specific questions there if you like.

Finally, we do intend to have a CUDA or OpenCL Monte-Carlo setup eventually, so if you have experience and time to build that, would be awesome, we'd need to discuss some on the architecture. Specifically, two scenarios we want to have are 1) run a single simulation on each GPU thread (Monte-Carlo style) and 2) parallelize a single simulation across GPU.

**Comment by maedoc** [comment]
doc tech noted [in the wiki](https://github.com/maedoc/sddekit/wiki/Docs)
