### ISSUE TITLE
C

### ISSUE THREAD

**Issue by maedoc** [maedoc/sddekit#84]
## changes to make
- [x] - use `uint32_t` & `bool` everywhere
- [x] - disambiguate error & stop condition in output objects
- [x] - valgrind & coverage on travis
- [x] - use single standard header with all the includes ([sddekit.h](https://github.com/maedoc/sddekit/blob/master/src/sddekit.h))
- [ ] - track allocated pointers, provide API for checking pointer is valid #107
- [x] - add [various sanitizers](https://news.ycombinator.com/item?id=10908042) to build test

## reading
- [link resources as binary blob](http://smackerelofopinion.blogspot.fr/2015/12/incorporating-and-accesses-binary-data.html?m=1)
- consider https://matt.sh/howto-c
- consider https://hintjens.gitbooks.io/scalable-c/content/chapter2.html
- consider http://crafn.kapsi.fi/new_engine.html
- https://news.ycombinator.com/item?id=10908042
- http://chickenwing.software/scratches/programming/annoying-apis
- [questionable tricks](http://stackoverflow.com/questions/599365/what-is-your-favorite-c-programming-trick?rq=1)

## tools

- [qira](http://qira.me/) time traveling (well, stateless) debugger for linux

**Comment by souravsingh** [comment]
I believe Valgrind is already integrated into Travis. Is the problem within the tests?

**Comment by maedoc** [comment]
correct I already had it in [.travis.yml](https://github.com/maedoc/sddekit/blob/master/.travis.yml#L13) but forgot the check the button.

**Comment by souravsingh** [comment]
About the issue for tracking allocated pointers,I think that could be done through Valgrind's Massif tool.

**Comment by maedoc** [comment]
Maybe but here I meant the second part of that line, having an API to check that a pointer is valid. This is important for a binding in higher-level language like MATLAB to ensure that user doesn't construct a a MATLAB-level object representing a C struct with an invalid pointer.

**Comment by maedoc** [comment]
Consider this closed for now, even with #107 outstanding, it can be covered later on.
